name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  flutter_spinkit: "^3.1.0"
  http: ^0.12.0+1
  splashscreen:
  # flutter_stetho: ^0.2.2

  cupertino_icons: ^0.1.2
  page_transition: "^1.0.9"
  flutter_sequence_animation: "^3.0.0"
  # animated_text_kit: ^1.3.0
  flutter_keychain: ^1.0.0
  bloc: ^0.13.0
  flutter_bloc: ^0.13.0
  equatable: ^0.1.0
  simple_animations: ^1.2.0
  provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  assets:
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
